### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by sehrcremig** [timkalkus/AutoReplace#6]
I enjoy the plugin. Would it be possible to add another feature Mister? It would be very lovely to switch automatically to the sword when I attack a mob. Thank you!

**Comment by timkalkus** [comment]
This plugin will (at least in the near future) only replace tools, selecting the perfect tools/weapons is not the goal of this plugin. But there are [other alternatives](https://www.spigotmc.org/resources/besttools.81490/) if you want to add this functionality to your server.
